name: CI

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 22.x
          check-latest: true
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  dependabot:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      # Automerge dependabot pr if it's not major update
      - name: Automerge Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:major' }}
        run: |
          gh pr merge --auto --rebase "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}